# Generated by Django 5.2.10 on 2026-02-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_whatsapp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_whatsapp_count',
            new_name='whatsapp_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_whatsapp_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_whatsapp_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
