# Generated by Django 5.2.10 on 2026-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_daily_whatsapp_count_userprofile_whatsapp_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
