# Generated by Django 5.2.10 on 2026-01-23 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
