# Generated by Django 5.2.10 on 2026-02-11 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
