# Generated by Django 5.2.10 on 2026-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='whatsapp_status',
            field=models.CharField(default='not_sent', max_length=20),
        ),
    ]
