# Generated by Django 5.2.10 on 2026-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_whatsapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='whatsapp_message_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
